version: '3'

volumes:
  mysql:
    driver: local
  fedora:
    driver: local

services:
  mysql:
    restart: always
    image: mysql:5.7
    env_file: .env_fedora
    command: --init-file /data/init.sql
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data:/data
    ports:
      - "3306:3306"

  fedora:
    restart: always
    image: pcharoen/era-java:1.3
    env_file:
      - .env_fedora
    depends_on: 
      - mysql
    command: bin/wait-for-it.sh -t 0 mysql:3306 -- tomcat/bin/catalina.sh run
    volumes:
      - /home/sumrarn/era:/home/sumrarn/era
      - /export/digital/era:/export/digital/era
      - ./wait-for-it.sh:/home/sumrarn/era/fedora-3.1/bin/wait-for-it.sh
    ports:
      - "8080:8080"
      - "8443:8443"
      - "61616:61616"
      - "3306:3306"
